
["PWP Medicine Settings"]
	#Время (в тиках) между применениями аптечки (20 тиков = 1 секунда). По умолчанию: 40 (2 сек)
	#Range: 1 ~ 72000
	medkitApplyTime = 40
	#Минимальный урон, при котором может начаться кровотечение. По умолчанию: 3.0 ХП
	#Range: 0.0 ~ 1000.0
	bleedingDamageThreshold = 3.0
	#Шанс получения кровотечения (от 0.0 до 1.0, где 0.2 - это 20%). По умолчанию: 0.2
	#Range: 0.0 ~ 1.0
	bleedingChance = 0.2

