
["PWP Medicine Settings"]
	#Р’СЂРµРјСЏ (РІ С‚РёРєР°С…) РјРµР¶РґСѓ РїСЂРёРјРµРЅРµРЅРёСЏРјРё Р°РїС‚РµС‡РєРё (20 С‚РёРєРѕРІ = 1 СЃРµРєСѓРЅРґР°). РџРѕ СѓРјРѕР»С‡Р°РЅРёСЋ: 40 (2 СЃРµРє)
	#Range: 1 ~ 72000
	medkitApplyTime = 40
	#РњРёРЅРёРјР°Р»СЊРЅС‹Р№ СѓСЂРѕРЅ, РїСЂРё РєРѕС‚РѕСЂРѕРј РјРѕР¶РµС‚ РЅР°С‡Р°С‚СЊСЃСЏ РєСЂРѕРІРѕС‚РµС‡РµРЅРёРµ. РџРѕ СѓРјРѕР»С‡Р°РЅРёСЋ: 3.0 РҐРџ
	#Range: 0.0 ~ 1000.0
	bleedingDamageThreshold = 3.0
	#РЁР°РЅСЃ РїРѕР»СѓС‡РµРЅРёСЏ РєСЂРѕРІРѕС‚РµС‡РµРЅРёСЏ (РѕС‚ 0.0 РґРѕ 1.0, РіРґРµ 0.2 - СЌС‚Рѕ 20%). РџРѕ СѓРјРѕР»С‡Р°РЅРёСЋ: 0.2
	#Range: 0.0 ~ 1.0
	bleedingChance = 0.2

