
[gameplay]
	#Set true if you want to reload all your guns when respawn
	#жЇеђ¦ејЂеђЇй‡Ќз”џж—¶и‡ЄеЉЁиЈ…еЎ«еј№иЌЇ
	respawn_reload = true
	#Set false if you want to show kill indication ONLY while killing an entity with a gun
	#жЇеђ¦д»…ењЁдЅїз”ЁжћЄжў°е‡»жќЂз”џз‰©ж—¶и§¦еЏ‘е‡»жќЂжЏђз¤єз‰№ж•€
	global_indication = true
	#Set true if you want to refill your armor plate when respawn
	#жЇеђ¦ејЂеђЇй‡Ќз”џж—¶и‡ЄеЉЁдЅїз”ЁйІеј№жЏ’жќї
	respawn_auto_armor = true

