#ејЂеђЇеђЋпјЊе°†ењЁйј ж ‡з§»еЉЁе€°з‰©е“ЃдёЉж—¶й«дє®жѕз¤єжњ‰е…іиЃ”зљ„е…¶е®ѓз‰©е“ЃгЂ‚
enableShowItemRelation = true

["Melee Setting"]
	#е€—иЎЁй‡Њзљ„жћЄжў°дјљдЅњдёєиї‘ж€ж­¦е™ЁдЅїз”ЁпјЊејЂзЃ«е°†иў«ж›їжЌўдёєиї‘ж€ж”»е‡»гЂ‚дЅ еЏЇд»ҐжЊ‰F3+Hж‰“ејЂй«зє§жЏђз¤єжЎ†пјЊжџҐзњ‹з‰©е“Ѓзљ„GunIdж ‡з­ѕпјЊе°±еѓЏз¤єдѕ‹зљ„й‚Јж ·гЂ‚
	MeleeWeaponList = ["tacz:type_82", "tacz:type_83"]

["GunSmithTable Setting"]
	#ејЂеђЇеђЋпјЊењЁжћЄжў°е·ҐдЅњеЏ°е€¶йЂ дёњиҐїж—¶дјљеј№е‡єз›ёе…із‰©е“ЃжЏђз¤єгЂ‚
	enableCraftToast = true
	#ејЂеђЇеђЋпјЊдЅїз”ЁжћЄжў°е·ҐдЅњеЏ°е€¶дЅњдёњиҐїж—¶е°†иЇ»еЏ–е‘Ёиѕ№е®№е™Ёзљ„з‰©е“ЃгЂ‚
	enableContainerReader = true
	#ењЁиї™й‡ЊеЎ«е…Ґж­Јж•ґж•°пјЊеЌіе€¶дЅњдёњиҐїж—¶жЊ‰дЅЏSHIFTдјљж‰№й‡Џе€¶дЅњзљ„ж¬Ўж•°гЂ‚
	enableMassCraftTime = 4

["Attachment Setting"]
	#ењЁиї™й‡ЊеЎ«е…Ґж­Јж•ґж•°пјЊеЌіеЇ№й…Ќд»¶жЊ‰shiftж—¶жѕз¤єзљ„йЂ‚з”ЁжћЄжў°ж•°й‡ЏгЂ‚
	enableLessAllowGun = 16
	#ејЂеђЇеђЋпјЊй…Ќд»¶е°†жѕз¤єиЇ¦з»†ж•°еЂјгЂ‚
	enableAttachmentDetail = true

["Other Setting"]
	#ејЂеђЇеђЋпјЊе¦‚жћњж­Је¤„дєЋйќћз¬¬дёЂдєєз§°и§†и§’пјЊдЅїз”ЁжћЄжў°зћ„е‡†е°†и‡ЄеЉЁе€‡жЌўдёєз¬¬дёЂдєєз§°пјЊеЏ–ж¶€зћ„е‡†еђЋе€‡жЌўдёєеЋџи§†и§’гЂ‚
	enableBetterAimCamera = true
	#ејЂеђЇеђЋпјЊе€‡жћЄе°†жІЎжњ‰еђЋж‘‡гЂ‚
	enableFastSwapGun = true

